### ISSUE TITLE
Windows 10 Pro NL is installing Education N NL version

### ISSUE THREAD

**Issue by hogendoorn** [OSDeploy/OSDCloud#13] opened 2022-05-31 20:34 UTC
**Describe the bug**
When  i try to instal Windows 10 Pro NL Windows 10 Education N version is actually installed.

**To Reproduce**
See screenshots.

**Expected behavior**
Installing the correct version.

**Screenshots**
![Screenshot_6](https://user-images.githubusercontent.com/12395796/171275036-f7ce2d9c-6e8c-4623-81ef-c8fa7ef287a6.jpg)
![Screenshot_7](https://user-images.githubusercontent.com/12395796/171275059-507b6a5c-2418-4196-a2c4-3d7575b18548.jpg)

**Comment by OSDeploy** [comment] 2022-06-01 01:20
Thanks. Do you have any idea on what the proper Index should be?

**Comment by hogendoorn** [comment] 2022-06-01 15:05
@OSDeploy After downloaden:

![image](https://user-images.githubusercontent.com/12395796/171436879-1b0ae683-5ce5-4fad-a8a5-3b1fd86c6aa1.png)

and running:
dism /Get-WimInfo /WimFile:D:\OSDCloud\OS\19044.1288.211006-0501.21h2_release_svc_refresh_CLIENTCONSUMER_RET_x64FRE_nl-nl.esd

![image](https://user-images.githubusercontent.com/12395796/171436725-07c8b2dd-b643-4e04-a898-e70ae74c3490.png)

Is this good info for the change?

**Comment by hogendoorn** [comment] 2022-06-09 07:48
Copying a install.wim to USB:\OSDCLOUD\OS from a downloaded iso is a good workaround so far. When selecting the right index it also installs the chosen index.

**Comment by dennisvl92** [comment] 2022-06-10 11:13
I have the same problem. I noticed that the imageindex gets adjusted 2 times.
This results in the index getting changed from 9 to 7 instead of 8
![screen](https://user-images.githubusercontent.com/35175545/173052850-0aebd2c9-3f69-492f-8723-78fc9c0d2196.png)

**Comment by OSDeploy** [comment] 2022-06-11 04:30
> 

Ok this helps. The issue is some media doesn't have Home Single Edition so I have to make a correction ... now I see it is being done twice. I'll get that tested this weekend, my apologies for the delay

**Comment by OSDeploy** [comment] 2022-06-11 06:42
Most of the ESD's contain a Home Single Edition image, so this issue only happens on ESD's that do not contain this Windows Image. To correct this issue, I have resolved the error where the Index was shifted by -1 twice.  So this should now work.  As you can see from this screenshot, NL-NL Pro Retail is assumed to be Index 9
![image](https://user-images.githubusercontent.com/12970006/173176639-c84d1ad7-a0f7-49cc-b29c-7458fd51bf1f.png)

But since the Image count is less than expected, because Home Single Edition is not part of the ESD, the ImageIndex gets adjusted by -1. Additionally, I have added a listing of the Windows Images (greater than 3GB to hide the Windows Setup and WinPE indexes) so you can validate. Finally, after Expand-WindowsImage, I am running a Get-WindowsImage to return the installed Windows Image. I hope this works and I'll push this out in OSD 22.6.11.1. Let me know if this works and I can close this issue
![image](https://user-images.githubusercontent.com/12970006/173176729-287775ae-110b-4e09-b825-6777bc97a4d3.png)

**Comment by dennisvl92** [comment] 2022-06-14 13:48
Yes it is working now. Thanks

**Closed** 2022-06-14 14:13 UTC
Labels: bug

**Comment by hogendoorn** [comment] 2022-07-19 12:34
Sorry for the delay. But it works!
